# Generated by Django 4.2.6 on 2023-10-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRUDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int', models.IntegerField()),
                ('char', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'CRUD_model',
                'verbose_name_plural': 'CRUD_models',
                'db_table': 'crud_model',
                'ordering': ['-id'],
            },
        ),
    ]
